include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false   # To avoid wearning when using print statement
analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
